# .pre-commit-config.yaml
- repo: https://github.com/psf/black
  rev: 23.7.0  # Use the latest stable version of Black
  hooks:
    - id: black
      language_version: python3

- repo: https://github.com/charliermarsh/ruff
  rev: v0.0.298  # Use the latest stable version of Ruff
  hooks:
    - id: ruff
      language_version: python3

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991  # Use the latest stable version of mypy
  hooks:
    - id: mypy
      language_version: python3

